### ISSUE TITLE
To set up a node, run make -j 4 Failed to compile.

### ISSUE THREAD

**Issue by COLUD4** [akme/ton-node#2]
![截屏2021-12-23 下午3 52 19](https://user-images.githubusercontent.com/21240219/147207077-68dc8666-04fd-4ec5-a49e-b463693247ad.png)

**Comment by COLUD4** [comment]
![截屏2021-12-23 下午6 03 42](https://user-images.githubusercontent.com/21240219/147224307-9dff21ee-3e7f-45f2-ac51-15548644ebaa.png)
Perform startup command (/ MNT/tonmain/core/ton/build/validator - engine/validator - engine - C/MNT/tonmain/node/config/global config. The json - db / MNT/tonmain/node/data - l/MNT/tonmain/node/data/debug log), log an error

**Comment by knox0506** [comment]
> ![截屏2021-12-23 下午3 52 19](https://user-images.githubusercontent.com/21240219/147207077-68dc8666-04fd-4ec5-a49e-b463693247ad.png)

yy

**Comment by knox0506** [comment]
UQCoqJ_l1MFeaSWrlpFK2uzNL1mrEc2hZSI8pNUs2DvxjGl8
